version: "3.8"

services:
  agent:
    image: grafana/agent:latest
    environment:
      - AGENT_MODE=flow
    volumes: 
      - $PWD/agent/config.river:/etc/agent/config.river
    ports:
      - 12345:12345
      - 44318:4318
    command: run --server.http.listen-addr=0.0.0.0:12345 /etc/agent/config.river

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - '$PWD/loki/loki-config.yml:/etc/loki/loki-config.yml'
    command: -config.file=/etc/loki/loki-config.yml

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - $PWD/tempo/tempo.yml:/etc/tempo.yml
      - tempo_data:/tmp/tempo
    ports:
      # - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "4317"  # otlp grpc
      - "4318"  # otlp http
      # - "9411"   # zipkin

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3999:3000'

volumes:
  tempo_data:
